/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.pidev.GUI.Formateur;

import edu.esprit.pidev.dao.classes.ChapitreDAO;
import edu.esprit.pidev.dao.interfaces.IChapitre;
import edu.esprit.pidev.entities.Chapitre;
import edu.esprit.pidev.entities.Cours;
import java.awt.Dimension;
import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Ahmed
 */
public class AjoutChapitrePanel extends javax.swing.JPanel {
//private static Cours c;
int id_Cours;
    /**
     * Creates new form AjoutChapitrePanel
     */
    public AjoutChapitrePanel(int id_Cours) {
        this.id_Cours=id_Cours;
        //this.c=c;
        initComponents();
        this.setOpaque(false);
        initComponents();
        setSize(new Dimension(716, 449));
        repaint();
        revalidate();
        System.out.println(getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        titre1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        URL1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Chapitre");

        titre1.setForeground(new java.awt.Color(153, 153, 153));
        titre1.setText("titre");
        titre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titre1ActionPerformed(evt);
            }
        });

        jButton1.setText("parcourir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        URL1.setForeground(new java.awt.Color(153, 153, 153));
        URL1.setText("URL de video");
        URL1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URL1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Ajouter les chapitres");

        jButton4.setText("Confirmer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(titre1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(URL1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titre1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(URL1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton4)
                .addContainerGap(188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void titre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titre1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser= new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        String filename= f.getAbsolutePath();
        URL1.setText(filename);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void URL1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URL1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URL1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Chapitre chapitre1 = new Chapitre();
       
        System.out.println(id_Cours);
        chapitre1.setTitre(titre1.getText());
        chapitre1.setURL(URL1.getText());
         //chapitre1.setId_Cours(id_Cours);
       // chapitre1.setId_Cours(c);
        System.out.println(URL1.getText());
        /*  if(titre2.getText().equals("")){
            chapitre2.setTitre(titre2.getText());
            chapitre1.setURL(URL2.getText());
            chapitre3.setTitre(titre3.getText());
            chapitre1.setURL(URL3.getText());
        }*/

        IChapitre chapitreDAO = new ChapitreDAO();
        try {

            chapitreDAO.AjouterChapitre(chapitre1);
            /* if(titre2.getText().equals("")){
                chapitreDAO.AjouterChapitre(chapitre2);        // TODO add your handling code here:
                chapitreDAO.AjouterChapitre(chapitre3);        // TODO add your handling code here:
            }*/
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(AjoutChapitrePanel.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:        // TODO add your handling code here:        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField URL1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField titre1;
    // End of variables declaration//GEN-END:variables
}
