/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.pidev.GUI.Formateur;

import edu.esprit.pidev.GUI.Apprenant.JCommentaireCours;
import static edu.esprit.pidev.GUI.Formateur.ModifierCoursPanel.S;
import edu.esprit.pidev.dao.classes.CoursApprenantDAO;
import edu.esprit.pidev.dao.classes.CoursDAO;
import edu.esprit.pidev.dao.classes.NotificationDAO;
import edu.esprit.pidev.entities.Cours;
import edu.esprit.pidev.entities.CoursApprenant;
import edu.esprit.pidev.entities.Notification;
import edu.esprit.pidev.entities.User;
import java.awt.Dimension;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Ahmed
 */
public class ConsulterCoursPanel extends javax.swing.JPanel {
private static Cours c;
int idCours=1;
private static User utilisateur;

    /**
     * Creates new form ConsulterCoursPanel
     */
    public ConsulterCoursPanel(Cours c,User utilisateur) {
             this.c=c;
              this.utilisateur=utilisateur;
            initComponents();
            setSize(new Dimension(771, 421));
            this.removeAll();
            repaint();
            revalidate();
             System.out.println(getHeight());
           int  idd=c.getIdCours();
           System.out.println("kokok"+idd);
        titre.setText(c.getTitre());
        cat.setText(c.getCategorie());
        diff.setText(c.getDifficult());
        desc.setText(c.getDescription());
        int idCours=c.getIdCours();
        this.idCours=idCours;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        desc = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        diff = new javax.swing.JLabel();
        cat = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Commenter = new javax.swing.JToggleButton();
        etoile1 = new javax.swing.JLabel();
        etoile2 = new javax.swing.JLabel();
        etoile3 = new javax.swing.JLabel();
        etoile4 = new javax.swing.JLabel();
        etoile5 = new javax.swing.JLabel();
        NoteLabel = new javax.swing.JLabel();

        jLabel7.setText("Noter Cours");

        desc.setText("jLabel9");

        jButton1.setText("Suivre ce Cour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        diff.setText("jLabel8");

        cat.setText("jLabel7");

        titre.setText("jLabel6");

        jLabel5.setText("Description");

        jLabel4.setText("Difficulté : ");

        jLabel3.setText("Categorie :");

        jLabel2.setText("titre :");

        jLabel1.setText("Afficher cours");

        Commenter.setText("Commenter");
        Commenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommenterActionPerformed(evt);
            }
        });

        etoile1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/pidev/images/EtoileNull.png"))); // NOI18N
        etoile1.setText("jLabel7");
        etoile1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etoile1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etoile1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etoile1MouseExited(evt);
            }
        });

        etoile2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/pidev/images/EtoileNull.png"))); // NOI18N
        etoile2.setText("jLabel8");
        etoile2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etoile2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etoile2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etoile2MouseExited(evt);
            }
        });

        etoile3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/pidev/images/EtoileNull.png"))); // NOI18N
        etoile3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etoile3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etoile3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etoile3MouseExited(evt);
            }
        });

        etoile4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/pidev/images/EtoileNull.png"))); // NOI18N
        etoile4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etoile4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etoile4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etoile4MouseExited(evt);
            }
        });

        etoile5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/pidev/images/EtoileNull.png"))); // NOI18N
        etoile5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etoile5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etoile5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etoile5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel2)
                .addGap(171, 171, 171)
                .addComponent(titre))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel3)
                .addGap(144, 144, 144)
                .addComponent(cat))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel4)
                .addGap(144, 144, 144)
                .addComponent(diff))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel5)
                .addGap(143, 143, 143)
                .addComponent(desc))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(Commenter))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(etoile1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(etoile2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(etoile3)
                .addGap(6, 6, 6)
                .addComponent(etoile4)
                .addGap(6, 6, 6)
                .addComponent(etoile5))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addComponent(NoteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(titre))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cat))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(diff))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(desc))
                .addGap(70, 70, 70)
                .addComponent(jButton1)
                .addGap(81, 81, 81)
                .addComponent(Commenter, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etoile1)
                    .addComponent(etoile2)
                    .addComponent(etoile3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etoile4)
                    .addComponent(etoile5))
                .addGap(37, 37, 37)
                .addComponent(NoteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jPanel1.removeAll();
        jPanel1.repaint();
        jPanel1.revalidate();
        jPanel1.add(new ChapitrePanel(idCours));
        jPanel1.repaint();
        jPanel1.revalidate();

        Notification nt = new Notification();
        NotificationDAO ntD= new NotificationDAO() ;
        CoursDAO coursDAO = new CoursDAO();

        CoursApprenant cr= new CoursApprenant();
        cr.setIdCours(c);
        System.out.println(c.getIdCours());

        cr.setIdUtilisateur(utilisateur);
        System.out.println(utilisateur.getId());
        SimpleDateFormat formater =new SimpleDateFormat("dd-MM-yyyy");

        Date date =new Date();
        cr.setDate(formater.format(date));
        CoursApprenantDAO crDAO = new CoursApprenantDAO();
        crDAO.ajout_coursApprenant(cr);
        ImageIcon done = new ImageIcon("src/edu/esprit/pidev/Presentation/img/done.png");
        int option = JOptionPane.showConfirmDialog(null, "Inscription avec succée !!", "Message", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE,done);

        String msg = " faire un inscrit au cours suivant : "+idCours;
        //ntD.add_notif_2(msg,Frame_Authentification.id_user+, coursDAO.disp_by_id(id).getIdCours(), id);

        ntD.add_notification(msg,formater.format(date),utilisateur.getId(),c.getIdCours());
        new ChapitrePanel(idCours).setVisible(true);
        System.out.println(idCours);

        this.setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void etoile1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etoile1MouseClicked
        // TODO add your handling code here:
         NoteLabel.setText("1/5"); 
       
        Cours cour= new Cours();
        CoursDAO cr= new CoursDAO();
      //  int i= listcours.gedIdCours ();
        cour=cr.findCoursByID(idCours);
        int note=Math.round((cour.getNote()+1)/2);
        cr.updateNoteCours(idCours, note);
       
        NoteLabel.setText(cour.getNote()+"/5");
    }//GEN-LAST:event_etoile1MouseClicked

    private void etoile1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etoile1MouseEntered
        // TODO add your handling code here:
        ImageIcon VI = new ImageIcon(getClass().getResource("/edu/esprit/pidev/images/EtoileFull.png"));
        etoile1.setIcon(VI); 
        NoteLabel.setText("1/5");
    }//GEN-LAST:event_etoile1MouseEntered

    private void etoile1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etoile1MouseExited
        // TODO add your handling code here:
         ImageIcon VI = new ImageIcon(getClass().getResource("/edu/esprit/pidev/images/EtoileNull.png"));
        etoile1.setIcon(VI);
        NoteLabel.setText("0/5");
    }//GEN-LAST:event_etoile1MouseExited

    private void etoile2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etoile2MouseClicked
        // TODO add your handling code here:
         NoteLabel.setText("2/5");  
         Cours cour= new Cours();
        CoursDAO cr= new CoursDAO();
      //  int i= listcours.gedIdCours ();
        cour=cr.findCoursByID(idCours);
        int note=Math.round((cour.getNote()+1)/2);
        cr.updateNoteCours(idCours, note);
       
        NoteLabel.setText(cour.getNote()+"/5");
    }//GEN-LAST:event_etoile2MouseClicked

    private void etoile2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etoile2MouseEntered
        // TODO add your handling code here:
        ImageIcon VI = new ImageIcon(getClass().getResource("/edu/esprit/pidev/images/EtoileFull.png"));
        etoile1.setIcon(VI); 
        etoile2.setIcon(VI); 
        NoteLabel.setText("2/5");
    }//GEN-LAST:event_etoile2MouseEntered

    private void etoile2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etoile2MouseExited
        // TODO add your handling code here:
         ImageIcon I = new ImageIcon(getClass().getResource("/edu/esprit/pidev/images/EtoileNull.png"));
      etoile1.setIcon(I);
      etoile2.setIcon(I);       
        NoteLabel.setText("0/5");
    }//GEN-LAST:event_etoile2MouseExited

    private void etoile3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etoile3MouseClicked
        // TODO add your handling code here:
         NoteLabel.setText("3/5");  
          Cours cour= new Cours();
        CoursDAO cr= new CoursDAO();
      //  int i= listcours.gedIdCours ();
        cour=cr.findCoursByID(idCours);
           int note=Math.round((cour.getNote()+3)/2);
        cr.updateNoteCours(idCours, note);
       
        NoteLabel.setText(cour.getNote()+"/5");
    }//GEN-LAST:event_etoile3MouseClicked

    private void etoile3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etoile3MouseEntered
        // TODO add your handling code here:
        ImageIcon I = new ImageIcon(getClass().getResource("/edu/esprit/pidev/images/EtoileFull.png"));
        etoile1.setIcon(I); 
        etoile2.setIcon(I);
        etoile3.setIcon(I);
        NoteLabel.setText("3/5");
    }//GEN-LAST:event_etoile3MouseEntered

    private void etoile3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etoile3MouseExited
        // TODO add your handling code here:
        ImageIcon I = new ImageIcon(getClass().getResource("/edu/esprit/pidev/images/EtoileNull.png"));
        etoile1.setIcon(I); 
        etoile2.setIcon(I);
        etoile3.setIcon(I);
        NoteLabel.setText("0/5");
    }//GEN-LAST:event_etoile3MouseExited

    private void etoile4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etoile4MouseClicked
        // TODO add your handling code here:
        NoteLabel.setText("4/5");  
         Cours cour= new Cours();
        CoursDAO cr= new CoursDAO();
      //  int i= listcours.gedIdCours ();
        cour=cr.findCoursByID(idCours);
       int note=Math.round((cour.getNote()+4)/2);
        cr.updateNoteCours(idCours, note);
       
        NoteLabel.setText(cour.getNote()+"/5");
    }//GEN-LAST:event_etoile4MouseClicked

    private void etoile4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etoile4MouseEntered
        // TODO add your handling code here:
            ImageIcon I = new ImageIcon(getClass().getResource("/edu/esprit/pidev/images/EtoileFull.png"));
        etoile1.setIcon(I); 
        etoile2.setIcon(I);
        etoile3.setIcon(I); 
        etoile4.setIcon(I);
        NoteLabel.setText("4/5");
         
    }//GEN-LAST:event_etoile4MouseEntered

    private void etoile4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etoile4MouseExited
        // TODO add your handling code here:
         ImageIcon I = new ImageIcon(getClass().getResource("/edu/esprit/pidev/images/EtoileNull.png"));
        etoile1.setIcon(I); 
        etoile2.setIcon(I);
        etoile3.setIcon(I); 
        etoile4.setIcon(I);
         NoteLabel.setText("0/5");
    }//GEN-LAST:event_etoile4MouseExited

    private void etoile5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etoile5MouseClicked
        // TODO add your handling code here:
        NoteLabel.setText("5/5");  
         Cours cour= new Cours();
        CoursDAO cr= new CoursDAO();
      //  int i= listcours.gedIdCours ();
        cour=cr.findCoursByID(idCours);
        int note=Math.round((cour.getNote()+5)/2);
        cr.updateNoteCours(idCours, note);
       
        NoteLabel.setText(cour.getNote()+"/5");
    }//GEN-LAST:event_etoile5MouseClicked

    private void etoile5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etoile5MouseEntered
        // TODO add your handling code here:
        ImageIcon I = new ImageIcon(getClass().getResource("/edu/esprit/pidev/images/EtoileFull.png"));
        etoile1.setIcon(I); 
        etoile2.setIcon(I);
        etoile3.setIcon(I); 
        etoile4.setIcon(I); 
        etoile5.setIcon(I);
        NoteLabel.setText("5/5");
    }//GEN-LAST:event_etoile5MouseEntered

    private void etoile5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etoile5MouseExited
        // TODO add your handling code here:
        ImageIcon I = new ImageIcon(getClass().getResource("/edu/esprit/pidev/images/EtoileNull.png"));
        etoile1.setIcon(I); 
        etoile2.setIcon(I);
        etoile3.setIcon(I); 
        etoile4.setIcon(I); 
        etoile5.setIcon(I);
         NoteLabel.setText("0/5");
    }//GEN-LAST:event_etoile5MouseExited

    private void CommenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommenterActionPerformed
        // TODO add your handling code here:
      new JCommentaireCours();
    }//GEN-LAST:event_CommenterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Commenter;
    private javax.swing.JLabel NoteLabel;
    private javax.swing.JLabel cat;
    private javax.swing.JLabel desc;
    private javax.swing.JLabel diff;
    private javax.swing.JLabel etoile1;
    private javax.swing.JLabel etoile2;
    private javax.swing.JLabel etoile3;
    private javax.swing.JLabel etoile4;
    private javax.swing.JLabel etoile5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
