/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.esprit.pidev.GUI.Organisme;


import edu.esprit.pidev.dao.classes.UtilisateurDAO;
import edu.esprit.pidev.entities.Mail;
import edu.esprit.pidev.entities.Rendez_vous;
import edu.esprit.pidev.entities.User;


import edu.esprit.pidev.util.MailConstruction;
import edu.esprit.pidev.dao.interfaces.Irendez_vousDAO;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Rihab
 */
public class AddredezVous extends javax.swing.JPanel {
Mail mail = new Mail();
       String role ; 
       int id_user ; 
    /**
     * Creates new form AddredezVous
     */
    public AddredezVous() {
         initComponents();
       this.role="a:1:{i:0;s:14:\"ROLE_FORMATEUR\";}";
       this.id_user=3;
        UtilisateurDAO userdao = new UtilisateurDAO();
       List <User> formateur = new ArrayList<User>();
       List <User> organisme=new ArrayList<User>();
       formateur=userdao.AfficherFormateur();
       organisme=userdao.DisplayOrganisme();
        if (role.equals("a:1:{i:0;s:14:\"ROLE_ORGANISME\";}")) {
            for (User l : formateur)
            {
                Formateur.addItem(l.getUsername());
            }
        } if (role.equals("a:1:{i:0;s:14:\"ROLE_FORMATEUR\";}")) {
            for (User l : organisme)
            {
                Formateur.addItem(l.getUsername());
            }
        }
       
    }
public AddredezVous(String rol,int id_use) {
         initComponents();
       this.role=rol;
       this.id_user=id_use;
          System.out.println("addrendez"+role);
          System.out.println("addrendez"+id_user);
         UtilisateurDAO userdao = new UtilisateurDAO();
       List <User> formateur = new ArrayList<User>();
       List <User> organisme=new ArrayList<User>();
       formateur=userdao.AfficherFormateur();
       organisme=userdao.DisplayOrganisme();
        if (role.equals("a:1:{i:0;s:14:\"ROLE_ORGANISME\";}")) {
            for (User l : formateur)
            {
                Formateur.addItem(l.getUsername());
            }
        } if (role.equals("a:1:{i:0;s:14:\"ROLE_FORMATEUR\";}")) {
            for (User l : organisme)
            {
                Formateur.addItem(l.getUsername());
            }
        }
 
        
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        duree = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        heure = new javax.swing.JSpinner();
        minute = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel5 = new javax.swing.JLabel();
        Formateur = new javax.swing.JComboBox();

        duree.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1h", "2h", "3h", "4h", "5h", "6h", " ", " " }));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/pidev/images/admin/rendez-vous.png"))); // NOI18N
        jLabel1.setText("Ajouter un  Rendez vous ");

        heure.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));

        minute.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));

        jLabel2.setText("Heure");

        jLabel3.setText("Minute");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/pidev/images/admin/geolocalisation_1.png"))); // NOI18N
        jButton2.setText("ajouter lieu et valider");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Durée");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Date");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Formateur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        Formateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormateurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(heure, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(minute, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(duree, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(Formateur, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jButton2)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(heure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(minute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(duree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addComponent(Formateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(44, 44, 44)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //
        //        //Durée
        String dur = duree.getSelectedItem().toString();
        //        //clandrier
        Date date = jCalendar1.getCalendar().getTime();
        Timestamp d = new Timestamp(date.getTime());
        int heu=(int) heure.getValue();
        int min = (int) minute.getValue();
        d.setHours(heu);
        d.setMinutes(min);
        d.setSeconds(00);
        //        //System.out.println("date "+d);
        //        //DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        //        //String dd = dateFormat.format(d);
        //        //formateur
        String formateur = Formateur.getSelectedItem().toString();

        System.out.println(formateur);
        UtilisateurDAO userdao = new UtilisateurDAO();
        int id =userdao.findUserByLogin(formateur);

        //System.out.println(id);
        Rendez_vous rdv=new Rendez_vous();
        rdv.setDuree_Rendezvous(dur);
        rdv.setDate_rendez_vous(d);
        if(role.equals("a:1:{i:0;s:14:\"ROLE_ORGANISME\";}")){
            rdv.setId_user(id);
            rdv.setId_organisme(id_user);
        }
        if (role.equals("a:1:{i:0;s:14:\"ROLE_FORMATEUR\";}")){
            rdv.setId_user(id_user);
            rdv.setId_organisme(id);}
        MapsChoose localisation =new MapsChoose(rdv);
        localisation.setVisible(true);
        this.setVisible(false);

        //email

        UtilisateurDAO login=new UtilisateurDAO();
        User user= new User();
        String adressemail=login.findadressebylogin(formateur);
        // String nom=login.findnombyid(id_user);
        user=login.findUtilisateurByID(id_user);
        String datere=d.toString();
        System.out.println(user);
        String msg="vous avez un rendez vous de "+user.getNom()+" "+user.getPrenom()+" le "+ d +" durée "+ dur +"  vous devez le consulter sur le mooc";
        //System.out.println(msg);

        mail.setMailObject(msg);
        // mail.setMailSubject("Mot de passe oublié");

        MailConstruction mc = new MailConstruction();
        mc.getMailProperties();

        mc.getMailMessage(mail,adressemail);
        mc.SendMessage();

        this.setVisible(false);

        //JOptionPane.showMessageDialog(this, "Ajout effectué avec succès et envoyer par E-mail ");
        //JOptionPane.showMessageDialog(this, "Votre E-mail est envoyé!!");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void FormateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormateurActionPerformed

    }//GEN-LAST:event_FormateurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Formateur;
    private javax.swing.JComboBox duree;
    private javax.swing.JSpinner heure;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner minute;
    // End of variables declaration//GEN-END:variables
}
