/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.pidev.GUI.Admin;

import edu.esprit.pidev.GUI.Admin.outils.StatChapitrePanel;
import edu.esprit.pidev.GUI.Admin.outils.StatComptePanel;
import edu.esprit.pidev.GUI.Admin.outils.StatForumPanel;
import edu.esprit.pidev.GUI.Admin.outils.StatNombrePanel;
import edu.esprit.pidev.GUI.Admin.outils.StatProjetPanel;
import edu.esprit.pidev.adapters.adapterStat.StatCoursTableModel;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Rihab
 */
public class StatistiquesPanel extends javax.swing.JPanel {

    private JFrame frame;
    private JPanel statPanel;

    /**
     * Creates new form StatistiquesPanel
     */
    public StatistiquesPanel(JFrame frame) {
        initComponents();
        this.frame = frame;
        statPanel = new StatProjetPanel();
        add(statPanel, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        ChartOptionsPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        comboEvolution = new javax.swing.JComboBox();
        refresh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestion des statistiques"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        ChartOptionsPanel.setMinimumSize(new java.awt.Dimension(650, 100));
        ChartOptionsPanel.setPreferredSize(new java.awt.Dimension(650, 100));
        ChartOptionsPanel.setLayout(new java.awt.GridBagLayout());

        jLabel3.setText("Evolution des statistiques sur : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(18, 5, 20, 5);
        ChartOptionsPanel.add(jLabel3, gridBagConstraints);

        comboEvolution.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Les cours les plus visités","Les sujets les plus Consultés","Les cours Contenant le plus de chapitres","Nombre des utilisateurs connectés","Nombre des utilisateurs par role"}));
        comboEvolution.setMinimumSize(new java.awt.Dimension(120, 20));
        comboEvolution.setPreferredSize(new java.awt.Dimension(150, 20));
        comboEvolution.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEvolutionItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 20, 14);
        ChartOptionsPanel.add(comboEvolution, gridBagConstraints);

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/pidev/Presentation/img/menuBar/reload.png"))); // NOI18N
        refresh.setText("Rafraichir");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 20, 14);
        ChartOptionsPanel.add(refresh, gridBagConstraints);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/pidev/Presentation/img/menuBar/save.png"))); // NOI18N
        jButton1.setText("Enregistrer la figure");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(18, 0, 20, 14);
        ChartOptionsPanel.add(jButton1, gridBagConstraints);

        jPanel1.add(ChartOptionsPanel, java.awt.BorderLayout.WEST);

        jPanel2.setMinimumSize(new java.awt.Dimension(250, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 100));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/pidev/Presentation/img/stat.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jLabel1, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String sb = "TEST CONTENT";
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("/Documents"));
        int retrival = chooser.showSaveDialog(null);
        if (retrival == JFileChooser.APPROVE_OPTION) {
            try {
                //rafraichir la vue du panel
                Container c = statPanel;
                BufferedImage im = new BufferedImage(c.getWidth(), c.getHeight(), BufferedImage.TYPE_INT_ARGB);
                c.paint(im.getGraphics());

                ImageIO.write(im, "PNG", new File(chooser.getSelectedFile() + ".png"));
                      JOptionPane.showMessageDialog(null,"Image enregistrée avec succès ! ","Image enregistrée ! ",JOptionPane.INFORMATION_MESSAGE);
               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"L'enregistrement de l'image est échoué ! ","Image nonenregistrée ! ",JOptionPane.INFORMATION_MESSAGE);
                System.out.println(e.getMessage());
            }
        }

            //585

    }//GEN-LAST:event_jButton1ActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        if (comboEvolution.getSelectedIndex() == 0){
            statPanel = new StatProjetPanel();
        } else if (comboEvolution.getSelectedIndex() == 1) {
           statPanel = new StatForumPanel();
        }
            add(statPanel, BorderLayout.CENTER);
    }//GEN-LAST:event_refreshActionPerformed

    private void comboEvolutionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEvolutionItemStateChanged
        if (comboEvolution.getSelectedIndex() == 0) {
            statPanel.setVisible(false);
           statPanel = new StatProjetPanel();
        } else if (comboEvolution.getSelectedIndex() == 1) {
            statPanel.setVisible(false);
           statPanel = new StatForumPanel();
        }
        else if (comboEvolution.getSelectedIndex() == 2) {
            statPanel.setVisible(false);
           statPanel = new StatChapitrePanel();
        }
        else if (comboEvolution.getSelectedIndex() == 3) {
            statPanel.setVisible(false);
           statPanel = new StatNombrePanel();
        }
        else if (comboEvolution.getSelectedIndex() == 4) {
            statPanel.setVisible(false);
           statPanel = new StatComptePanel();
        }
        
            add(statPanel, BorderLayout.CENTER);
    }//GEN-LAST:event_comboEvolutionItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChartOptionsPanel;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JComboBox comboEvolution;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton refresh;
    // End of variables declaration//GEN-END:variables
}
