/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.esprit.pidev.GUI.Apprenant;

import edu.esprit.pidev.adapters.Verif;
import edu.esprit.pidev.dao.classes.UtilisateurDAO;
import edu.esprit.pidev.entities.Mail;
import edu.esprit.pidev.entities.User;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jb2011.lnf.beautyeye.ch3_button.BEButtonUI;

/**
 *
 * @author soumaya
 */
  /**
     * Creates new form EmailPanel
     */
public class EmailPanel extends javax.swing.JPanel {
    URL url;
    Mail mail = new Mail();
    private User user;
  
    List <User> formateur = new ArrayList<User>();
    Integer index ;
    private Object jLabelpieceJointe;
    
    
    public EmailPanel(User user) {
        this.user= user;
        initComponents();
         UtilisateurDAO userdao = new UtilisateurDAO();
        
//        formateur=userdao.DisplayFormateur();
               
                for (User l : formateur)
                {
                    ListeFormateur.addItem(l.getEmail());
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextArearObject = new javax.swing.JPanel();
        jTextMailAddressSender = new javax.swing.JTextField();
        jPassworSender = new javax.swing.JPasswordField();
        jTextmailsubject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonSendMail = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ListeFormateur = new javax.swing.JComboBox();
        upload = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jTextArearObject.setLayout(null);

        jTextMailAddressSender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMailAddressSenderActionPerformed(evt);
            }
        });
        jTextArearObject.add(jTextMailAddressSender);
        jTextMailAddressSender.setBounds(281, 25, 269, 32);
        jTextArearObject.add(jPassworSender);
        jPassworSender.setBounds(281, 67, 269, 32);
        jTextArearObject.add(jTextmailsubject);
        jTextmailsubject.setBounds(281, 151, 269, 32);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArearObject.add(jScrollPane1);
        jScrollPane1.setBounds(281, 193, 269, 106);

        jLabel2.setText("Votre adresse Email ");
        jTextArearObject.add(jLabel2);
        jLabel2.setBounds(105, 33, 119, 16);

        jLabel3.setText("Mot de passe Email");
        jTextArearObject.add(jLabel3);
        jLabel3.setBounds(105, 75, 111, 16);

        jLabel4.setText("Email du destinataire");
        jTextArearObject.add(jLabel4);
        jLabel4.setBounds(105, 117, 120, 16);

        jLabel5.setText("Sujet");
        jTextArearObject.add(jLabel5);
        jLabel5.setBounds(105, 159, 30, 16);

        jLabel6.setText("Contenue");
        jTextArearObject.add(jLabel6);
        jLabel6.setBounds(105, 193, 54, 16);

        jButtonSendMail.setText("Envoyer");
        jButtonSendMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendMailActionPerformed(evt);
            }
        });
        jTextArearObject.add(jButtonSendMail);
        jButtonSendMail.setBounds(300, 370, 230, 35);

        jLabel7.setText("Pièce jointe");
        jTextArearObject.add(jLabel7);
        jLabel7.setBounds(105, 318, 66, 16);

        ListeFormateur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        ListeFormateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeFormateurActionPerformed(evt);
            }
        });
        jTextArearObject.add(ListeFormateur);
        ListeFormateur.setBounds(280, 110, 270, 30);

        upload.setUI (new BEButtonUI (). setNormalColor (BEButtonUI.NormalColor.lightBlue));
        upload.setForeground(new java.awt.Color(255, 255, 255));
        upload.setText("Uploader un fichier");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        jTextArearObject.add(upload);
        upload.setBounds(280, 310, 170, 40);

        add(jTextArearObject, java.awt.BorderLayout.CENTER);

        jPanel1.setPreferredSize(new java.awt.Dimension(167, 160));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/pidev/Presentation/img/email.png"))); // NOI18N
        jLabel8.setMaximumSize(new java.awt.Dimension(567, 150));
        jLabel8.setMinimumSize(new java.awt.Dimension(567, 120));
        jLabel8.setPreferredSize(new java.awt.Dimension(567, 250));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(32, 0, 10, 0);
        jPanel1.add(jLabel8, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSendMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendMailActionPerformed
      if(Verif.isValidEMail(jTextMailAddressSender.getText())
          && Verif.isValidEMail((String) ListeFormateur.getSelectedItem())
          && jPassworSender.getText()!=""
          && jTextmailsubject.getText()!=""
          && jTextArea1.getText()!=""
         ){
        mail.setMailAddressRecipient((String) ListeFormateur.getSelectedItem());
        mail.setPwd(jPassworSender.getText());
        mail.setMailAddressSender(jTextMailAddressSender.getText());
        mail.setMailSubject(jTextmailsubject.getText());
        String[] lines = jTextArea1.getText().split("\\n");
        String msg="";
        for(String s:lines){
            msg = msg+s;
        }
        mail.setMailObject(msg);
        MailConstruction mc = new MailConstruction();
        mc.getMailProperties();
        
        String s ="" ;
        if (url!=null)
            s= this.cleanUrl(url);
        else
            JOptionPane.showMessageDialog(null,"Vous n'avez pas séléctionner une pièce jointe,\n Le transfert du message continuera...","Pas de piéce jointe ! ",JOptionPane.WARNING_MESSAGE);
              
        mc.getMailMessage(s, mail);
        mc.SendMessage();
            JOptionPane.showMessageDialog(null,"Votre message a été envoyé avec succès !","Erreur",JOptionPane.INFORMATION_MESSAGE);
        
       }else{
                      JOptionPane.showMessageDialog(null,"Champs invalides !","Champs invalides ! ",JOptionPane.WARNING_MESSAGE);     
       }
        
                                    
        
       
        
    }//GEN-LAST:event_jButtonSendMailActionPerformed
    public String cleanUrl(URL url){
        
        String s = url.toString();
        System.out.println("Before Clean");
        System.out.println(s);
        String delims = "/";
        String[] tokens = s.split(delims);
        System.out.println("After Clean");
        String mailPart="";
        for (int i=1;i<tokens.length;i++){
            mailPart+=tokens[i]+"\\\\";
        }
        System.out.println(mailPart);
        return mailPart;
    }
    private void jTextMailAddressSenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMailAddressSenderActionPerformed
        jTextMailAddressSender.setText("azezae");
    }//GEN-LAST:event_jTextMailAddressSenderActionPerformed

    private void ListeFormateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeFormateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ListeFormateurActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        JFileChooser chooser = new JFileChooser();
        int option = chooser.showOpenDialog(null);
        if(option == JFileChooser.APPROVE_OPTION){
            try{
                URL url = chooser.getSelectedFile().toURL();
                System.out.println(url);
                //jLabelpieceJointe.setText(url.toString());

            }
            catch(MalformedURLException exception){
                System.out.println("The URL was malformed ... ");

            }
        }
    }//GEN-LAST:event_uploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ListeFormateur;
    private javax.swing.JButton jButtonSendMail;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassworSender;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel jTextArearObject;
    private javax.swing.JTextField jTextMailAddressSender;
    private javax.swing.JTextField jTextmailsubject;
    private javax.swing.JButton upload;
    // End of variables declaration//GEN-END:variables
}
