/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.pidev.GUI.Apprenant;
import static edu.esprit.pidev.GUI.GuiCommite.setTheme;
import edu.esprit.pidev.dao.classes.UtilisateurDAO;
import edu.esprit.pidev.entities.User;

import java.io.File;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Rihab
 */
public class Inscription extends javax.swing.JFrame {

  
    public Inscription() {
        setTheme();
        initComponents();
         jDateChooser1.setDateFormatString("yyyy-MM-dd");
       
        setTitle("MOOC v1.0 - Inscription");
	setLocationRelativeTo(null);
        //setSize(getToolkit().getScreenSize().width,getToolkit().getScreenSize().height); 
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(this);
        
        setVisible(true);
         t_CV.setVisible(false);
        jButtonCV.setVisible(false);
        jLabel11.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonCV = new javax.swing.JLabel();
        t_CV = new javax.swing.JTextField();
        jButtonInscription = new javax.swing.JButton();
        ROrganisme = new javax.swing.JRadioButton();
        RFormateur = new javax.swing.JRadioButton();
        RApprenant = new javax.swing.JRadioButton();
        RHomme3 = new javax.swing.JRadioButton();
        Rfemme = new javax.swing.JRadioButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        t_log = new javax.swing.JTextField();
        t_email = new javax.swing.JTextField();
        t_confpass = new javax.swing.JPasswordField();
        t_pass = new javax.swing.JPasswordField();
        t_prenom = new javax.swing.JTextField();
        t_nom = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Retour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nom :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Prenom :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Mot de passe :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Confirmation de mot de passe :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("E-mail :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Login :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Date de naissance :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Sexe :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Êtes-vous :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Ajouter votre cv");

        jButtonCV.setForeground(new java.awt.Color(153, 0, 0));
        jButtonCV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/pidev/Presentation/img/fichier-pdf-icone-8882-32.png"))); // NOI18N
        jButtonCV.setText("sélectionner une fichier");
        jButtonCV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCVMouseClicked(evt);
            }
        });

        jButtonInscription.setBackground(new java.awt.Color(251, 208, 151));
        jButtonInscription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonInscription.setText("Inscription");
        jButtonInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInscriptionActionPerformed(evt);
            }
        });

        ROrganisme.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ROrganisme.setForeground(new java.awt.Color(51, 51, 51));
        ROrganisme.setText("Organisme");
        ROrganisme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ROrganismeActionPerformed(evt);
            }
        });

        RFormateur.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        RFormateur.setForeground(new java.awt.Color(51, 51, 51));
        RFormateur.setText("Formateur");
        RFormateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFormateurActionPerformed(evt);
            }
        });

        RApprenant.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        RApprenant.setForeground(new java.awt.Color(51, 51, 51));
        RApprenant.setText("Apprenant");
        RApprenant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RApprenantActionPerformed(evt);
            }
        });

        RHomme3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        RHomme3.setForeground(new java.awt.Color(51, 51, 51));
        RHomme3.setText("Homme");
        RHomme3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RHomme3ActionPerformed(evt);
            }
        });

        Rfemme.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Rfemme.setForeground(new java.awt.Color(51, 51, 51));
        Rfemme.setText("Femme");
        Rfemme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RfemmeActionPerformed(evt);
            }
        });

        t_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(179, 63, 64));
        jLabel10.setText("Inscription ");
        jLabel10.setAlignmentX(0.5F);

        jLabel9.setBackground(new java.awt.Color(255, 204, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(179, 63, 64));
        jLabel9.setText("C'est gratuit ( et ça le restera toujours ) ");

        Retour.setBackground(new java.awt.Color(251, 208, 151));
        Retour.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Retour.setText("Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(720, Short.MAX_VALUE)
                .addComponent(jButtonInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(163, 163, 163)
                            .addComponent(t_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(163, 163, 163)
                            .addComponent(t_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(163, 163, 163)
                            .addComponent(t_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(t_confpass, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(163, 163, 163)
                            .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(163, 163, 163)
                            .addComponent(t_log, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(122, 122, 122)
                            .addComponent(RHomme3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(90, 90, 90)
                            .addComponent(Rfemme, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(122, 122, 122)
                            .addComponent(RApprenant)
                            .addGap(7, 7, 7)
                            .addComponent(RFormateur, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(ROrganisme, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(66, 66, 66)
                            .addComponent(jButtonCV, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(t_CV, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(653, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Retour, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInscription, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(t_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_confpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_log, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RHomme3)
                        .addComponent(Rfemme))
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RApprenant)
                        .addComponent(RFormateur)
                        .addComponent(ROrganisme))
                    .addGap(30, 30, 30)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_CV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 134, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCVMouseClicked

        JFileChooser chooser= new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        String filename= f.getAbsolutePath();
        t_CV.setText(filename);

    }//GEN-LAST:event_jButtonCVMouseClicked

    private void jButtonInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInscriptionActionPerformed
        int etat = 0;
        int en=1;
        String s;
        String roles,cv = null;
        User u =null;
        SymfonyEncoder se = new SymfonyEncoder("SHA-512"); 
        

        //             if (!rempliComplet())
        //                {
            //                    JOptionPane.showMessageDialog(rootPane, "Veulliez remplir tout le formulaire !");
            //                }
        String na=t_nom.getText();
        String pr=t_prenom.getText();
        String ps=t_pass.getText();
        //String cf=t_confpass.getText();
       String  salt="";
        String em=t_email.getText();
        String log=t_log.getText();
        String usr_can=t_log.getText();
        String email_canonical= t_email.getText();
        
        String dt =((JTextField)  jDateChooser1.getDateEditor().getUiComponent()).getText();

        if ( t_nom.getText().equals("")||!Pattern.matches("[A-Za-z][a-zA-Z\\s]*", t_nom.getText()))
        { JOptionPane.showMessageDialog(null, "champ nom invalide", "Erreur", JOptionPane.ERROR_MESSAGE);  }

        else if ( t_prenom.getText().equals("")||!Pattern.matches("[A-Za-z][a-zA-Z\\s]*", t_prenom.getText()))
        {  JOptionPane.showMessageDialog(null, "champ  prenom invalide", "Erreur", JOptionPane.ERROR_MESSAGE);          }

        else if(!t_confpass.getText().equals(t_pass.getText()))
        { JOptionPane.showMessageDialog(null, " le deux password ne sont pas identiques ", "Erreur", JOptionPane.ERROR_MESSAGE);  }

        else if(t_email.getText().equals("")||!Pattern.matches("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@([\\w]+\\.)+[\\w]+[\\w]$", t_email.getText()))
        { JOptionPane.showMessageDialog(null, " champ mail invalide", "Erreur", JOptionPane.ERROR_MESSAGE);  }

        else if(new UtilisateurDAO().recherchemail(t_email.getText())!=0)
        { JOptionPane.showMessageDialog(null, "Adresse mail exist", "Erreur", JOptionPane.ERROR_MESSAGE);  }

        else if ( t_log.getText().equals("")||!Pattern.matches("\\w*", t_log.getText()))
        { JOptionPane.showMessageDialog(null, "champ login invalide", "Erreur", JOptionPane.ERROR_MESSAGE);  }

        else if(  new UtilisateurDAO().recherchelogin(t_log.getText())!=0 )
        { JOptionPane.showMessageDialog(null, "Login exist", "Erreur", JOptionPane.ERROR_MESSAGE);   }

        else if ( jDateChooser1.getDate()==null)
        { JOptionPane.showMessageDialog(null, "Date invalide", "Erreur", JOptionPane.ERROR_MESSAGE);             }
        else
        {
            if (RHomme3.isSelected())
            s="Homme";
            else
            s="Femme";
            if (RApprenant.isSelected() )
            {
                
                se.setPass_clair(ps);
                se.genererSalt();
                se.crypterPass();
                ps=se.getPass_crypte();
                salt=se.getSalt();
                roles="a:1:{i:0;s:14:\"ROLE_APPRENANT\";}";
                u = new User (na,pr,dt,s,log,usr_can,em,email_canonical,en,salt,ps,roles);
            }
            else if (RFormateur.isSelected())
            {
                roles="a:1:{i:0;s:14:\"ROLE_FORMATEUR\";}";
                cv=t_CV.getText();
                se.setPass_clair(ps);
               // se.genererSalt();
                se.crypterPass();
                ps=se.getPass_crypte();
                //salt=se.getSalt();
                u = new User (na,pr,dt,s,log,usr_can,em,email_canonical,en,salt,ps,roles,cv);
            } 
            else
            {
                 se.setPass_clair(ps);
               // se.genererSalt();
                se.crypterPass();
                ps=se.getPass_crypte();
               // salt=se.getSalt();
                roles="a:1:{i:0;s:14:\"ROLE_ORGANISME\";}";
                 // t_Document.setVisible(true);
                u = new User (na,pr,dt,s,log,usr_can,em,email_canonical,en,salt,ps,roles);
                //doc=t_Document.getText();

            }

          

            UtilisateurDAO UserDao= new UtilisateurDAO();
            UserDao.addApprenant(u);
            JOptionPane.showMessageDialog(this,"Insertion validée");

            RHomme3.setSelected(false);
            Rfemme.setSelected(false);
            RApprenant.setSelected(false);
            ROrganisme.setSelected(false);
            RFormateur.setSelected(false);
            jLabel11.setVisible(false);
        }
    }//GEN-LAST:event_jButtonInscriptionActionPerformed

    private void ROrganismeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ROrganismeActionPerformed
        if(ROrganisme.isSelected())
        {
            RApprenant.setSelected(false);
            RFormateur.setSelected(false);
            t_CV.setVisible(false);         
            jButtonCV.setVisible(false);
            jLabel11.setVisible(false);
        
        }
    }//GEN-LAST:event_ROrganismeActionPerformed

    private void RFormateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFormateurActionPerformed
         if(RFormateur.isSelected())
        {
            t_CV.setVisible(true);
            jButtonCV.setVisible(true);
            RApprenant.setSelected(false);
            ROrganisme.setSelected(false);
            jLabel11.setVisible(true);
            
        }
    }//GEN-LAST:event_RFormateurActionPerformed

    private void RApprenantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RApprenantActionPerformed
        if (RApprenant.isSelected())
        {
            ROrganisme.setSelected(false);
            RFormateur.setSelected(false);
            t_CV.setVisible(false);
            jButtonCV.setVisible(false);
            jLabel11.setVisible(false);
        }
    }//GEN-LAST:event_RApprenantActionPerformed

    private void RHomme3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RHomme3ActionPerformed
        if (RHomme3.isSelected())
        Rfemme.setSelected(false);
    }//GEN-LAST:event_RHomme3ActionPerformed

    private void RfemmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RfemmeActionPerformed
        if (Rfemme.isSelected())
        RHomme3.setSelected(false);
    }//GEN-LAST:event_RfemmeActionPerformed

    private void t_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passActionPerformed

    private void RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetourActionPerformed
        Connexion1 A=new  Connexion1 ();
        this.dispose();
        A.setVisible(true);
    }//GEN-LAST:event_RetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RApprenant;
    private javax.swing.JRadioButton RFormateur;
    private javax.swing.JRadioButton RHomme3;
    private javax.swing.JRadioButton ROrganisme;
    private javax.swing.JButton Retour;
    private javax.swing.JRadioButton Rfemme;
    private javax.swing.JLabel jButtonCV;
    private javax.swing.JButton jButtonInscription;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t_CV;
    private javax.swing.JPasswordField t_confpass;
    private javax.swing.JTextField t_email;
    private javax.swing.JTextField t_log;
    private javax.swing.JTextField t_nom;
    private javax.swing.JPasswordField t_pass;
    private javax.swing.JTextField t_prenom;
    // End of variables declaration//GEN-END:variables
}
