package edu.esprit.pidev.GUI.Comite;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import edu.esprit.pidev.dao.classes.CoursDAO;
import edu.esprit.pidev.entities.Cours;
import edu.esprit.pidev.entities.User;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jb2011.lnf.beautyeye.ch3_button.BEButtonUI;

/**
 *
 * @author kenza
 */
public class JAfficherUnCours extends javax.swing.JPanel {

    /**
     * Creates new form JAfficherUnProjet
     */
    private Cours c;

    public Cours getC() {
        return c;
    }

    public void setC(Cours c) {
        this.c = c;
        
    }
    
    public JAfficherUnCours() {
        initComponents();
    }
    
    private User user;
     public JAfficherUnCours(Cours c,User user ) {
         this.user = user;
    this.setVisible(true);
        initComponents();
        this.c=c;
      
           CoursDAO cd = new CoursDAO();
         System.out.println(c.getNbrChapitre());
        categoriefd.setText(c.getCategorie());
        titrefd.setText(c.getTitre());
        chapitrefd.setText(String.valueOf(c.getNbrChapitre()));
        difficultéfd.setText(c.getDifficult());
        statutfd.setText(c.getEtat());
        descriptionfd.setText(c.getDescription());
     /*   if(p.getEtatInitial().equals("affecté"))
        {
             mailtext.setText(cdao.);
        }
       */
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        panelRight = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        statutfd = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        ajouterTestBoutton = new javax.swing.JButton();
        panelLeft = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        categoriefd = new javax.swing.JTextField();
        chapitrefd = new javax.swing.JTextField();
        difficultéfd = new javax.swing.JTextField();
        titrefd = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        descriptionfd = new javax.swing.JTextArea();

        setMinimumSize(new java.awt.Dimension(582, 419));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(755, 120));
        jPanel1.setPreferredSize(new java.awt.Dimension(582, 120));
        jPanel1.setLayout(new java.awt.GridBagLayout());
        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        panelRight.setMinimumSize(new java.awt.Dimension(280, 220));
        panelRight.setPreferredSize(new java.awt.Dimension(320, 348));
        panelRight.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Statut", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.setMinimumSize(new java.awt.Dimension(260, 70));
        jPanel2.setPreferredSize(new java.awt.Dimension(260, 50));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        statutfd.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 118;
        gridBagConstraints.insets = new java.awt.Insets(8, 75, 18, 74);
        jPanel2.add(statutfd, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 0, 7);
        panelRight.add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Candidature", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(260, 106));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Voir Vidéo");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 43, 3, 0);
        jPanel3.add(jButton1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 0, 7);
        panelRight.add(jPanel3, gridBagConstraints);
        jPanel3.getAccessibleContext().setAccessibleName("Vidéo");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Test d'acceptaion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(260, 80));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        ajouterTestBoutton.setUI (new BEButtonUI (). setNormalColor (BEButtonUI.NormalColor.green));
        ajouterTestBoutton.setForeground(new java.awt.Color(255, 255, 255));
        ajouterTestBoutton.setText("Ajouter");
        ajouterTestBoutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ajouterTestBoutton.setMaximumSize(new java.awt.Dimension(131, 23));
        ajouterTestBoutton.setMinimumSize(new java.awt.Dimension(131, 23));
        ajouterTestBoutton.setPreferredSize(new java.awt.Dimension(131, 23));
        ajouterTestBoutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterTestBouttonMouseClicked(evt);
            }
        });
        ajouterTestBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterTestBouttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 44, 8, 46);
        jPanel5.add(ajouterTestBoutton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.insets = new java.awt.Insets(10, 12, 12, 7);
        panelRight.add(jPanel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel6.add(panelRight, gridBagConstraints);

        panelLeft.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Titre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 12, 0, 0);
        panelLeft.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Catégorie");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        panelLeft.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Difficulté");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        panelLeft.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Nombre Des Chapitres");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        panelLeft.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Description");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        panelLeft.add(jLabel5, gridBagConstraints);

        categoriefd.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 9, 0);
        panelLeft.add(categoriefd, gridBagConstraints);

        chapitrefd.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 9, 0);
        panelLeft.add(chapitrefd, gridBagConstraints);

        difficultéfd.setEditable(false);
        difficultéfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultéfdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 0, 9, 0);
        panelLeft.add(difficultéfd, gridBagConstraints);

        titrefd.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 160;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 9, 0);
        panelLeft.add(titrefd, gridBagConstraints);

        descriptionfd.setEditable(false);
        descriptionfd.setColumns(20);
        descriptionfd.setRows(5);
        descriptionfd.setPreferredSize(new java.awt.Dimension(6, 20));
        scroll.setViewportView(descriptionfd);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 9, 0);
        panelLeft.add(scroll, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel6.add(panelLeft, gridBagConstraints);

        add(jPanel6, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ajouterTestBouttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterTestBouttonMouseClicked
       JAjoutTestAcceptation jfta = new JAjoutTestAcceptation(c);
       jfta.setVisible(true);
    }//GEN-LAST:event_ajouterTestBouttonMouseClicked

    private void difficultéfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultéfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_difficultéfdActionPerformed

    private void ajouterTestBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterTestBouttonActionPerformed
          
        /*if(c.getEtat().equals("valider"))
        {
             JOptionPane.showMessageDialog(this, "  Le cours est déjà validé ");
        }*/
       if (c.getEtat().equals("attente"))
        {
        JAjoutTestAcceptation jat= new JAjoutTestAcceptation(c);
        JFrame jfta = new JFrame();
        jfta.add(jat);
        jfta.setSize(450, 350);
        jfta.setLocationRelativeTo(this);
        jfta.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jfta.setVisible(true);
        }
        
    }//GEN-LAST:event_ajouterTestBouttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// pour ahmeed
//       
//        JFrame jf1 = new JFrame();
//        jf1.add(jpcp);
//        jf1.setSize(700, 300);
//        jf1.setLocationRelativeTo(this);
//        jf1.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//        jf1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterTestBoutton;
    private javax.swing.JTextField categoriefd;
    private javax.swing.JTextField chapitrefd;
    private javax.swing.JTextArea descriptionfd;
    private javax.swing.JTextField difficultéfd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField statutfd;
    private javax.swing.JTextField titrefd;
    // End of variables declaration//GEN-END:variables
}

