/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.pidev.GUI.Comite;


import edu.esprit.pidev.dao.classes.CoursDAO;
import edu.esprit.pidev.dao.classes.UtilisateurDAO;
import edu.esprit.pidev.entities.Cours;
import edu.esprit.pidev.entities.TestAcceptation;
import edu.esprit.pidev.entities.User;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import org.jb2011.lnf.beautyeye.ch3_button.BEButtonUI;

/**
 *
 * @author kenza
 */
public class JAjoutTestAcceptation extends javax.swing.JPanel {

    private Cours c;
    private User u;

    public User getU() {
        return u;
    }

    public void setU(User u) {
        this.u = u;
    }

    public Cours getC() {
        return c;
    }

    public void setP(Cours c) {
        this.c = c;

    }

    /**
     * Creates new form JAjoutTestAcceptation
     */
    public JAjoutTestAcceptation(Cours c1) {

        initComponents();
        this.c = c1;
        c.setIdCours(c1.getIdCours());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentaireBox = new javax.swing.JTextArea();
        jRadioNonValide = new javax.swing.JRadioButton();
        jRadioValide = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        enregistrerTestButton = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(300, 228));
        setPreferredSize(new java.awt.Dimension(519, 300));

        jPanel4.setMinimumSize(new java.awt.Dimension(300, 228));
        jPanel4.setPreferredSize(new java.awt.Dimension(519, 300));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(270, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 57));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/pidev/Presentation/img/testAcc.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 4, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jPanel1, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Commentaire");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 3);
        jPanel2.add(jLabel1, gridBagConstraints);

        commentaireBox.setColumns(20);
        commentaireBox.setRows(4);
        commentaireBox.setTabSize(6);
        jScrollPane1.setViewportView(commentaireBox);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 240;
        gridBagConstraints.ipady = 73;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 2, 11);
        jPanel2.add(jScrollPane1, gridBagConstraints);

        jRadioNonValide.setText("Non valide");
        jRadioNonValide.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioNonValideStateChanged(evt);
            }
        });
        jRadioNonValide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioNonValideActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 3, 0);
        jPanel2.add(jRadioNonValide, gridBagConstraints);

        jRadioValide.setText("Valide");
        jRadioValide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioValideActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 10);
        jPanel2.add(jRadioValide, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        enregistrerTestButton.setForeground(new java.awt.Color(255, 255, 255));
        enregistrerTestButton.setText("Enregistrer");
        enregistrerTestButton.setUI (new BEButtonUI (). setNormalColor (BEButtonUI.NormalColor.red));
        enregistrerTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enregistrerTestButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        jPanel3.add(enregistrerTestButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jPanel3, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enregistrerTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enregistrerTestButtonActionPerformed
        TestAcceptation ta = new TestAcceptation();
        UtilisateurDAO ut= new UtilisateurDAO(); 
        CoursDAO cd = new CoursDAO();
        
//partie modifiée *****************************
        if (jRadioValide.isSelected()) {
            ta.setValidation(true);
   
            c.setEtat("valider");
            cd.upDateCours(c);
            int idd=c.getIdCours();
            System.out.println("idd"+idd);
            JOptionPane.showMessageDialog(this, "  Le cours a bien été validé ");

        } else if (jRadioNonValide.isSelected()) {
            ta.setValidation(false);
          
            JOptionPane.showMessageDialog(this, "   Oups! Le cours est invalide! ");

        }
        ta.setCommentaire(commentaireBox.getText());
        ta.setCours(c);
        ta.setUser(u);

       
    }//GEN-LAST:event_enregistrerTestButtonActionPerformed

    private void jRadioNonValideStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioNonValideStateChanged
      
    }//GEN-LAST:event_jRadioNonValideStateChanged

    private void jRadioValideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioValideActionPerformed
          jRadioNonValide.setSelected(false);
           
    }//GEN-LAST:event_jRadioValideActionPerformed

    private void jRadioNonValideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioNonValideActionPerformed
         jRadioValide.setSelected(false);
          
    }//GEN-LAST:event_jRadioNonValideActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea commentaireBox;
    private javax.swing.JButton enregistrerTestButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioNonValide;
    private javax.swing.JRadioButton jRadioValide;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
