/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.esprit.pidev.GUI.Comite;



import edu.esprit.pidev.dao.classes.messageDao;
import edu.esprit.pidev.entities.User;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import org.jb2011.lnf.beautyeye.ch3_button.BEButtonUI;

/**
 *
 * @author Imen
 */
public class MessageAdminWindow extends javax.swing.JFrame {
    private User u;
    /**
     * Creates new form SignalerWindow
     */
    public MessageAdminWindow(User user) {
        this.u = user;
        Image im =  Toolkit.getDefaultToolkit().getImage("src\\Presentation\\img\\msgAdmin0.png");//icone
        setIconImage(im);
        
        initComponents();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenue = new javax.swing.JTextArea();
        titre = new javax.swing.JTextField();
        imgMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contacter l'administration");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(430, 543));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Type de message");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 5, 10);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Titre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Contenue");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        jPanel1.add(jLabel3, gridBagConstraints);

        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Envoyer");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setUI (new BEButtonUI (). setNormalColor (BEButtonUI.NormalColor.lightBlue));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 21, 10);
        jPanel1.add(jButton1, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Reclamation","Dysfonctionnement","Feedback" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(2, 10, 5, 10);
        jPanel1.add(jComboBox1, gridBagConstraints);

        contenue.setColumns(20);
        contenue.setRows(5);
        jScrollPane1.setViewportView(contenue);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.ipady = 67;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        jPanel1.add(jScrollPane1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        jPanel1.add(titre, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        imgMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/img/msgAdmin0.png"))); // NOI18N
        imgMsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imgMsg.setMinimumSize(new java.awt.Dimension(200, 200));
        imgMsg.setPreferredSize(new java.awt.Dimension(250, 206));
        getContentPane().add(imgMsg, java.awt.BorderLayout.NORTH);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //changement de l'icone et du couleur du bouton selon le choix dans la liste déroulante
        if (jComboBox1.getSelectedIndex()==0){
            imgMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/img/msgAdmin0.png")));
            jButton1.setUI (new BEButtonUI (). setNormalColor (BEButtonUI.NormalColor.lightBlue));

        } 
        else if (jComboBox1.getSelectedIndex()==1){
            imgMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/img/msgAdmin1.png")));
            jButton1.setUI (new BEButtonUI (). setNormalColor (BEButtonUI.NormalColor.red));

        } 
        else if (jComboBox1.getSelectedIndex()==2){
            imgMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentation/img/msgAdmin2.png")));
            jButton1.setUI (new BEButtonUI (). setNormalColor (BEButtonUI.NormalColor.green));

        } 
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        messageDao msgdao = new messageDao();
    
           if (contenue.getText().equals("") || titre.getText().equals("") ){
                 JOptionPane.showMessageDialog(null,"Vérifier les champs contenue et titre !","Message non envoyé !",JOptionPane.WARNING_MESSAGE);              
          
           }else

           {//type
        String type="";
            if (jComboBox1.getSelectedIndex() == 0) type ="Reclamation";
            else if (jComboBox1.getSelectedIndex() == 1) type ="Dysfonctionnement";
            else if (jComboBox1.getSelectedIndex() == 2) type ="Feedback";
            
        if (msgdao.insertMessage(titre.getText(), contenue.getText(),type,u.getUsername()))
             JOptionPane.showMessageDialog(null,"Merci, envoi effectué avec succès !\nNous traiterons votre message dans les plus brefs délais.","Message envoyé !",JOptionPane.INFORMATION_MESSAGE);              
        else
             JOptionPane.showMessageDialog(null,"Erreur d'envoi du message!","Message non envoyé !",JOptionPane.WARNING_MESSAGE);              
          
        dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessageAdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessageAdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessageAdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessageAdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessageAdminWindow(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea contenue;
    private javax.swing.JLabel imgMsg;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField titre;
    // End of variables declaration//GEN-END:variables
}
