package edu.esprit.pidev.GUI.Comite;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import edu.esprit.pidev.GUI.Comite.JAfficherUnCours;
import edu.esprit.pidev.adapters.JTableModelCoursAttente;
import edu.esprit.pidev.adapters.JTableModelCoursValide;
import edu.esprit.pidev.dao.classes.CoursDAO;
import edu.esprit.pidev.entities.Cours;
import edu.esprit.pidev.entities.User;
import java.awt.TextField;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicTreeUI;

/**
 *
 * @author kenza
 */
public class ValiderCoursPannel extends javax.swing.JPanel {

    /**
     * Creates new form JProjetAccueilJobOwnerPannel
     */
    private User user ;
    public ValiderCoursPannel(User user) {
        this.user = user;
        initComponents();
    }

    ValiderCoursPannel() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablecoursAttente = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablecoursValide = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        supprimerBoutton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jTabbedPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane3MouseClicked(evt);
            }
        });

        jTablecoursAttente.setModel(new JTableModelCoursAttente(user));
        jTablecoursAttente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablecoursAttenteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTablecoursAttente);

        jTabbedPane3.addTab("Cours en Attente", jScrollPane2);

        jTablecoursValide.setModel(new JTableModelCoursValide(user));
        jTablecoursValide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablecoursValideMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablecoursValide);

        jTabbedPane3.addTab("Cours Validés", jScrollPane1);

        add(jTabbedPane3, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Estrangelo Edessa", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/pidev/Presentation/img/gestProjet.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(211, 70));
        jLabel1.setMinimumSize(new java.awt.Dimension(211, 70));
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        supprimerBoutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/pidev/Presentation/img/menuBar/del.png"))); // NOI18N
        supprimerBoutton.setText("Supprimer Cours");
        supprimerBoutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        supprimerBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerBouttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 11, 0);
        jPanel5.add(supprimerBoutton, gridBagConstraints);

        add(jPanel5, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void supprimerBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerBouttonActionPerformed
   
        try {
            CoursDAO cd =new CoursDAO();
            JTableModelCoursAttente jt = new  JTableModelCoursAttente(user);
            JTableModelCoursValide jv= new JTableModelCoursValide(user);
            
            ////// pour jTableCoursAttente
            Cours c1=new Cours ();
            jTabbedPane3.getSelectedIndex();
            if(jTabbedPane3.getSelectedIndex()==1)
            {
              
                    int ligne = jTablecoursAttente.getSelectedRow();
                    c1.setIdCours(jt.getIDCours(ligne));
                    cd.SupprimerCours(ligne);
                    
                    jTablecoursAttente.setModel(new JTableModelCoursAttente(user));
               
            }
            ////// pour jTableProjetValide
            if(jTabbedPane3.getSelectedIndex()==2)
            {
                try {
                    int ligne = jTablecoursValide.getSelectedRow();
                    c1.setIdCours(jv.getIDCours(ligne));
                    
                    cd.SupprimerCours(c1);
                    
                    jTablecoursValide.setModel(new JTableModelCoursValide(user));
                } catch (SQLException ex) {
                    Logger.getLogger(ValiderCoursPannel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            Cours c = new Cours();
            int ligne2 = jTablecoursValide.getSelectedRow();
            int x = jTablecoursAttente.getSelectedRow();
            
            cd.SupprimerCours(c1);
            JOptionPane.showMessageDialog(this, "Le cours est supprimé  ");
            jTablecoursAttente.setModel(new JTableModelCoursValide(user));
        } catch (SQLException ex) {
            Logger.getLogger(ValiderCoursPannel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_supprimerBouttonActionPerformed

    private void jTabbedPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane3MouseClicked
       
    }//GEN-LAST:event_jTabbedPane3MouseClicked

    private void jTablecoursValideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablecoursValideMouseClicked
       JTableModelCoursValide jv=new JTableModelCoursValide(user);
        if(evt.getClickCount()==2)
        {

            Cours c1 = new Cours();
            jTabbedPane3.getSelectedIndex();
            if(jTabbedPane3.getSelectedIndex()==1)
            {
                int ligne2 = jTablecoursValide.getSelectedRow();
                String chaine2=jTablecoursValide.getValueAt(ligne2, 0).toString();
                c1.setTitre(chaine2);
                c1.setIdCours(jv.getListCours().get(ligne2).getIdCours());
                c1.setCategorie(jTablecoursValide.getValueAt(ligne2,1).toString());
                c1.setDescription(jTablecoursValide.getValueAt(ligne2,2).toString());
                c1.setDifficult(jTablecoursValide.getValueAt(ligne2,3).toString());
                c1.setEtat(jv.getListCours().get(ligne2).getEtat());
            }
            JAfficherUnCours aff = new JAfficherUnCours(c1,user);
            JFomTest3AffichageCours affiche = new JFomTest3AffichageCours(c1,user );
            affiche.setVisible(true);
        }

    }//GEN-LAST:event_jTablecoursValideMouseClicked

    private void jTablecoursAttenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablecoursAttenteMouseClicked
         JTableModelCoursAttente jt = new JTableModelCoursAttente(user);
        if(evt.getClickCount()==2)
        {
            ////// pour jTableCoursAttente
           
            Cours c1= new Cours();
            jTabbedPane3.getSelectedIndex();
            if(jTabbedPane3.getSelectedIndex()==0)
            {
                int ligne1 = jTablecoursAttente.getSelectedRow();
                String chaine1=jTablecoursAttente.getValueAt(ligne1, 0).toString();
                c1.setTitre(chaine1);
                c1.setIdCours(jt.getListCours().get(ligne1).getIdCours());
                c1.setCategorie(jTablecoursAttente.getValueAt(ligne1, 1).toString());
                c1.setDescription(jTablecoursAttente.getValueAt(ligne1, 2).toString());
                c1.setDifficult(jTablecoursAttente.getValueAt(ligne1,3).toString());
                c1.setEtat(jt.getListCours().get(ligne1).getEtat());
            }
            JAfficherUnCours aff = new JAfficherUnCours(c1,user);
            JFomTest3AffichageCours affiche = new JFomTest3AffichageCours(c1,user);
            affiche.setVisible(true);
        }
    }//GEN-LAST:event_jTablecoursAttenteMouseClicked

    
    
    
        
 public void JTableProjetAttenteAction(java.awt.event.ActionEvent evt)
 {
     jTablecoursAttente.addMouseListener(new MouseListener() {

         @Override
         public void mouseClicked(MouseEvent e) {
         
            Cours c = new Cours();
            c=(Cours) jTablecoursAttente.getValueAt(jTablecoursAttente.getSelectedRow(), 1);
             //permet de récupérer l'objet avec l'index de la ligne sélectionné 
         }

         @Override
         public void mousePressed(MouseEvent e) {     
         }

         @Override
         public void mouseReleased(MouseEvent e) {    
         }

         @Override
         public void mouseEntered(MouseEvent e) {   
         }

         @Override
         public void mouseExited(MouseEvent e) {    
         }
     });
 }
 
 
     
     public void JTableProjetValideAction(java.awt.event.ActionEvent evt)
 {
     jTablecoursValide.addMouseListener(new MouseListener() {

         @Override
         public void mouseClicked(MouseEvent e) {
      
          Cours c= new Cours ();
            c=(Cours) jTablecoursValide.getValueAt(jTablecoursValide.getSelectedRow(), 1);
             //permet de récupérer l'objet avec l'index de la ligne sélectionné
         }

         @Override
         public void mousePressed(MouseEvent e) {     
         }

         @Override
         public void mouseReleased(MouseEvent e) {    
         }

         @Override
         public void mouseEntered(MouseEvent e) {   
         }

         @Override
         public void mouseExited(MouseEvent e) {    
         }
     });
     
     
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTablecoursAttente;
    private javax.swing.JTable jTablecoursValide;
    private javax.swing.JButton supprimerBoutton;
    // End of variables declaration//GEN-END:variables
}



//**********************************************************
 

//**************************************************
 class JFomTest3AffichageCours extends javax.swing.JFrame {

    /**
     * Creates new form JFomTest3AffichageCours
     */
    static Cours c;
    private User user;
    public JFomTest3AffichageCours(Cours c,User user) {
        this.user = user;
        add(new JAfficherUnCours(c,user));
        this.setSize(780,550);
         this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setVisible(true);
        
    }
}

//***********************************************

    
